server:
  port: 8443
  mode: release
  timeout: 30s
  tls:
    enabled: true
    cert_file: ./certs/server.crt
    key_file: ./certs/server.key

security:
  jwt:
    secret: "9!t(vbe^e9&ojckngikkw65io^ks%4#w^h^c81j8tv=eq6n7bh" # To be set via environment variable JWT_SECRET
    expiry: 1h
  encryption:
    key_rotation_period: 90d
    algorithm: AES-256-GCM

database:
  postgres:
    host: localhost
    port: 5432
    database: hipaa_exchange
    user: "" # To be set via environment variable POSTGRES_USER
    password: "" # To be set via environment variable POSTGRES_PASSWORD
    ssl_mode: verify-full
    max_connections: 100
    connection_timeout: 10s
    statement_timeout: 30s
    idle_timeout: 10m
  redis:
    addr: localhost:6379
    password: "" # To be set via environment variable REDIS_PASSWORD
    db: 0
  elasticsearch:
    addresses: 
      - http://localhost:9200
    username: "" # To be set via environment variable ES_USERNAME
    password: "" # To be set via environment variable ES_PASSWORD

audit:
  enabled: true
  retention_period: 7y
  log_level: info

consent:
  expiry: 365d
  require_explicit: true
  renewal_reminder: 30d

monitoring:
  prometheus:
    enabled: true
    path: /metrics
  health_check:
    enabled: true
    path: /health

compliance:
  hipaa:
    enabled: true
    min_password_length: 12
    password_expiry: 90d
    session_timeout: 15m
    failed_login_attempts: 5
    lockout_duration: 30m
